// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjBf5UlUrKNAT7bgzHiMgwUpGlU7DTQiQ',
    appId: '1:750143042473:web:5de1e800a87f08d914cab8',
    messagingSenderId: '750143042473',
    projectId: 'website-test-c8b55',
    authDomain: 'website-test-c8b55.firebaseapp.com',
    storageBucket: 'website-test-c8b55.firebasestorage.app',
    measurementId: 'G-L9EBKS0FCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjBKK2-yiUjDWIgU1gKMO9fS4BzvnPoME',
    appId: '1:750143042473:android:b38084250079179e14cab8',
    messagingSenderId: '750143042473',
    projectId: 'website-test-c8b55',
    storageBucket: 'website-test-c8b55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyHk0vjtICxxnHRAEfHihfxgGt9AZQgjI',
    appId: '1:750143042473:ios:91df0f212e8aaddc14cab8',
    messagingSenderId: '750143042473',
    projectId: 'website-test-c8b55',
    storageBucket: 'website-test-c8b55.firebasestorage.app',
    iosBundleId: 'com.example.spendwise',
  );
}
